# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: PSGruss
google_analytics: UA-178196734-1
title: Gruss Tech Zone

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Gruss Tech Zone

description: Welcome to the Gruss Tech Zone
base_url: /
url: https://test.gruss.cloud
author:
  name: John Gruss
  email: john.gruss.4@gmail.com
  github: PSGruss
  twitter: 4gruss
  linkedin: johngruss
  bio: PowerShell Junkie, Automation Enthusiast
  email_md5: 5d355d4a8024958c2598729a61b9786a

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
sidebar_background_image: https://i.imgur.com/XWFfVg1.jpg

BASE_PATH:

plugins:
  - jekyll-paginate
